### ISSUE TITLE
New workflows container-v1.0.0 tags are not being bumped by renovate

### ISSUE THREAD

**Issue by JossWhittle** [SwanseaUniversityMedical/workflows#121]
https://github.com/SwanseaUniversityMedical/k8s-backups/issues/5

Not detecting the dependency to be bumped. Perhaps because it is not a pure semver tag.

**Comment by rdash99** [comment]
https://github.com/renovatebot/renovate/issues/2438#issuecomment-471027310 

Might be useful here
