### ISSUE TITLE
Allow for functionality to support releasing multiple assets bundled with the same tag

### ISSUE THREAD

**Issue by rdash99** [SwanseaUniversityMedical/workflows#171]
Some form of versioning job that leads into one or more containers/charts, passing the same tag to all of them (this would be a modified version of the existing workflows without the GitHub release component), then that comes back together into a workflow that purely handles the GitHub release. This would result in a three (kind of) job workflow in a target repo so that, for example, a chart could be released separately whilst two containers in the same repo are bundled together with their tags.

**Comment by JossWhittle** [comment]
- On `workflows-test` repo, create an example workflow file which calls a pre-job and then two containers build jobs that are dependent on it.
- Pre-job is a reusable workflow, probably just the `pr-and-release-repo.yaml` workflow after being patched to also return outputs of the version number it determined.
  - This workflow already handles only creating pr-labels when run on an open pr, and creating a github release when run on a release push.
- Container build jobs will be similar to current ones, handling both pr and release. But will need to be modified to not do the github release themselves and to just accept the version number as an additional input.
